### ISSUE TITLE
VRTK_Player_Presence dynamic collider height is broken

### ISSUE THREAD

**Issue by lepoup** [thestonefox/SteamVR_Unity_Toolkit#572] opened 2016-09-15 10:18 UTC
The collider height computation is broken after last VRTK_Player_Presence commit (cb6908b).
-Start 017 example. Move to the blue slope. The height collider bug is occuring

![player presence capsule height broken](https://cloud.githubusercontent.com/assets/21106484/18546469/6bfbe746-7b3e-11e6-873f-28b87c4f0597.jpg)

**Comment by thestonefox** [comment] 2016-09-15 10:19
Ok I'll take a look

**Comment by lepoup** [comment] 2016-09-15 10:31
It works again with transform.position instead of transform.localposition. But I don't know if the scale is still good.

var newpresenceColliderYSize = (headset.transform.position.y - headsetYOffset) - transform.position.y;

**Comment by thestonefox** [comment] 2016-09-15 10:32
that's what it was originally. I think the change was made to deal with scaling the camera rig.

I'll take a look at come up with something that works.

**Comment by mattboy64** [comment] 2016-09-15 15:48
Arrrg! Dang it! I'll take a look tonight if you don't get to it first

**Comment by thestonefox** [comment] 2016-09-15 15:49
Race!!! :D

**Comment by mattboy64** [comment] 2016-09-15 16:04
It works fine when the CameraRig is on the ground (0,0,0). I think the problem is because the calculation is using the Camera(Eye)'s local posiiton, when it should be using the Camera(Head).

**Comment by mattboy64** [comment] 2016-09-15 16:09
@thestonefox I think there's a bug in the VRTK_DeviceFinder. GetHeadset will return the Camera(eye) which doesn't move. Is there a way to get the Camera(Head)???

**Comment by mattboy64** [comment] 2016-09-15 16:25
K, got a hotfix, but it's a little hacky right now since we don't have access to the Camera(head). Replace the newpresenceColliderYSize definition with:
`var newpresenceColliderYSize = (headset.parent.transform.localPosition.y - headsetYOffset);`
and it will work.

A better fix would be to have VRTK_DeviceFinder have functionality to grab the Camera(head) in some fashion, but I think the whole Camera(eye)/Camera(head) thing is confusing, so thiere's probably some considerations to think about there.

**Comment by thestonefox** [comment] 2016-09-15 16:40
isn't the parent of the headset the CameraRig?

**Comment by thestonefox** [comment] 2016-09-15 16:41
also "Camera(Head)" doesn't exist at runtime in Unity 5.4 (does in 5.3)

**Comment by mattboy64** [comment] 2016-09-15 16:47
Maybe my setup is jacked up then, This is what I have: 
![image](https://cloud.githubusercontent.com/assets/7003769/18558806/58b15faa-7b29-11e6-9dfb-bfbee6a5bcee.png)

**Comment by thestonefox** [comment] 2016-09-15 16:47
Click play, and look at your Inspector then

**Comment by mattboy64** [comment] 2016-09-15 16:48
That is on play

**Comment by thestonefox** [comment] 2016-09-15 16:48
![image](https://cloud.githubusercontent.com/assets/1029673/18558859/a0fcfd94-7b6c-11e6-9e84-0e4adb48ba7a.png)

That's what I get on play

**Comment by mattboy64** [comment] 2016-09-15 16:49
What version of SteamVR are you on? Mine says SteamVR plugin for Unity - v1.1.1

**Comment by thestonefox** [comment] 2016-09-15 16:49
1.1.1

**Comment by mattboy64** [comment] 2016-09-15 16:50
Weird, maybe I have to do that cache clearing thing. 

Here's my prefab:
![image](https://cloud.githubusercontent.com/assets/7003769/18558914/d16bba08-7b29-11e6-952f-0239079e3572.png)

**Comment by thestonefox** [comment] 2016-09-15 16:51
Yeah the prefab still looks like that, but at runtime it switches

**Comment by mattboy64** [comment] 2016-09-15 16:52
Strange. Gotta figure that out. In the meantime try replacing it with this and seeing if it works: 
`var newpresenceColliderYSize = (headset.transform.localPosition.y - headsetYOffset);`

**Comment by thestonefox** [comment] 2016-09-15 16:56
i'll give it a whirl

**Comment by lepoup** [comment] 2016-09-15 17:09
This last one is working well on my side

**Comment by mattboy64** [comment] 2016-09-15 18:16
@thestonefox, does that means it's going to only work on 5.4? Is the Camera(head) thing from an older version of Unity or an old version of SteamVR?

**Comment by thestonefox** [comment] 2016-09-15 20:31
Fixed with https://github.com/thestonefox/SteamVR_Unity_Toolkit/commit/087b5679bafb9affd839f6247db9c19b328d86c4

**Closed by thestonefox** 2016-09-15 20:31 UTC
