### ISSUE TITLE
SteamVR_HeightAdjustTeleport causes CameraRig to fall through to lower collider.

### ISSUE THREAD

**Issue by kenjudytx** [thestonefox/SteamVR_Unity_Toolkit#112] opened 2016-05-30 00:59 UTC
**Situation**: Creating a scene where the CameraRig is above a GameObject Cube or the like, and there is another GameObject with a collider attached below the first.

**Problem**: When Play Space Falling is check the CameraRig will start on the bottom collider even though it is place above the top. (This happens even if the bottom is set to trigger)

**Attempted at Debugging**: A simple print statement inside DropToNearestFloor inside the rayHit if statement, shows it detects the first GameObject but then the second is detected and the CameraRig is placed there.

**Simple Fix**: I simply changed the following in  DropToNearestFloor
`SetNewPosition(newPosition, currentFloor.transform);`
to 
`SetNewPosition(newPosition+Vector3.up*.001f, currentFloor.transform);`

**Query**: _Is there a better way of handling this or am I doing something wrong in the first place?_ 

Note: This still seems to happen with the small fix, mainly when starting the scene with the headset being low/untracked.

**Comment by thestonefox** [comment] 2016-05-30 07:44
I can confirm I get the same issue. I'm looking into it now

**Comment by thestonefox** [comment] 2016-05-30 08:05
Figured out the issue. The problem is when the eyecamera is initialising it has the same Y position as the play area, so the very first ray that is cast is underneath the object you're standing on, then once the headset is initialised it is at the right height.

Fixed in commit: 39c27291e029feef737b66c6fdfdfd8e4a13db57

**Closed by thestonefox** 2016-05-30 08:05 UTC
