### ISSUE TITLE
Scene 021 - Unable to Swap Object Between Hands - Part Deux

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/SteamVR_Unity_Toolkit#61] opened 2016-05-15 00:05 UTC
You did fix the _dangle_, but still you can't pass objects between hands. Right now if I grab an object, then try to grab with the other hand, the moment I let of either grip, EVEN if I'm still gripping with one hand, the object falls. 

What should be expected is that if I grab an object, then grab with the other hand, the object is now parented to the new hand; the user should be able to pass between and reorient objects in their possession.

In a related note, the _floating between hands_ is back when grabbing the lamp with both hands. I'm able to then stretch my hands apart and still manipulate the lamp.

**Comment by thestonefox** [comment] 2016-05-15 05:03
The way it's working is you can actually have both controllers in a grabbing state , which is causing slight artifacts at the moment but in the future it will be polished so having both hands grabbed will mean an extra dimension (eg being able to size an object with your controllers, bit like pinch to zoom)

**Comment by thestonefox** [comment] 2016-05-15 10:50
Forgot to say, you can mitigate against the problem (in the current master branch version) by just setting the "Detatch Threshold" on the object to something really high (even infinity).

The issue is, the new controller parent applies a huge force to the object, therefore breaking all of the existing joints.

The new grabbing mechanism (the other branch you've tried). will prevent this joint breaking on parenting an new controller (when I've finished it) so this problem won't exist, hopefully by tomorrow! :)

**Comment by thestonefox** [comment] 2016-05-15 10:54
Actually I changed my mind, I'm going to close this with reference to the ticket that will fix it :)

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/54

**Closed by thestonefox** 2016-05-15 10:54 UTC
Labels: bug, enhancement

**Comment by xEvoGx** [comment] 2016-05-15 16:35
Perfect!
