### ISSUE TITLE
[Possible Bug] Unable to drop object when grabbed from certain angle

### ISSUE THREAD

**Issue by Tom-LeFx** [thestonefox/SteamVR_Unity_Toolkit#577] opened 2016-09-16 15:25 UTC
Hi,

we were able to create a scene to reproduce the bug.
The hand-scanner is positioned at the wall and can be grabbed by the user (Child-to-Controller-mode).
When you grab the scanner in the lower grip-area, you are able to return it to the "mount" without any issue...when you grab the controller by the top-side, you cannot drop it to the mount (or anywhere else)

Any help appreciated.

As attachments don't seem to work:
https://www.dropbox.com/s/08gdq1yo1r0v9sd/Undroppable_Scanner_Error.ZIP?dl=0

**Comment by Tom-LeFx** [comment] 2016-09-16 15:48
It's basically an example scene...we put together everything with new placeholders or meshes. The scene is madeup from ground up.

The only things altered from the "factory-defaults" are, that we added some logic to detect, whether you can drop an object or not (via collision-volume as trigger) and some logic to place the object exactly back to the position, where it should reside (done in the interact-grab-script)

**Comment by thestonefox** [comment] 2016-09-16 15:55
The issue could be in the additional logic though.

That's why it's best to have a recreation of the issue for steps in the example scene with the code untouched. Then if the issue is in the code of the toolkit I'll be able to find it easier.

**Comment by Tom-LeFx** [comment] 2016-09-16 16:22
Ok...i could narrow it down extremely:

The issue exists, when you choose "Child-of-Controller" and pick the two controllers as snap-handles as well.

Do that: Create an object, add "interact-grab" to it, set the settings like this :

Is Grabbable
Is Dropable
Right Snap Handle Controller Right
Left Snap Handle Controller Left
Mechanic Child_Of_Controller 

and try to pick up an object at it's top-side (if it's lying down, probably one of the sides instead of top) and then try to drop it again. For us, it's reproducible undroppable at this condition.
I don't know if it is due to user-error/intended behavior or bug

**Comment by thestonefox** [comment] 2016-09-16 20:29
You don't need to set the Snap handles to the controllers. in fact that will put the origin off the controller centre.

If you leave the snap handles as "non" then it will use the controller tip by default.

I'm guessing what your issue is, that because the snap position is so off centre, when you pick the object up the object's collider is not touching the controller collider maybe.

**Comment by thestonefox** [comment] 2016-09-16 20:34
also, what version of the toolkit are you using (github/asset store?)

I can recreate the issue where the object isn't touching the controller (because of the issue of setting the controller as the snap point which isn't a bug). but when i release the buttons i always drop the object, so maybe this is something that has been fixed in a newer version.

**Closed** 2016-10-01 06:42 UTC
