### ISSUE TITLE
Trouble with multiple radial menus

### ISSUE THREAD

**Issue by Bugzoo** [thestonefox/SteamVR_Unity_Toolkit#307] opened 2016-07-28 00:01 UTC
I've been trying for about a week but I still can't seem to fix it. When I make the radial menu inactive, I open another one, but the buttons on the first radial menu are still working. It's driving me mad

**Comment by thestonefox** [comment] 2016-07-28 07:22
Closing this as it's a duplicate of issue https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/293

**Closed by thestonefox** 2016-07-28 07:22 UTC
