### ISSUE TITLE
2 pointers required in order to use teleport

### ISSUE THREAD

**Issue by spaggi** [thestonefox/SteamVR_Unity_Toolkit#111] opened 2016-05-29 10:41 UTC
I'm new to Github and I do not really feel ready to mess with your code. 

I ran into some issues trying to get the simple teleporter to run. In SteamVR_BasicTeleport.cs you do the following when initializing:

` SteamVR_WorldPointer[] worldPointers = GameObject.FindObjectsOfType<SteamVR_WorldPointer>();

        // If the WorldPointer Object isn't initialised yet then retry in a quarter of a second
        // Because the Controller is a child of the CameraRig (and the WorldPointer is usually attached
        // to the Controller) then it is likely the WorldPointer object isn't available at start.
        if (worldPointers.Length != connectedControllers.Count)
        {
            if (listenerInitTries > 0)
            {
                listenerInitTries--;
            }
            else
            {
                retryListenersDelay = retryListenersDelay * retryListenerMultiplier;
                listenerInitTries = listenerInitMax;
                Debug.LogWarning("Waiting for controllers to initialise, retrying in " + retryListenersDelay);
            }
            Invoke("InitPointerListeners", retryListenersDelay);`

If I understand this correctly, your logic requires 2 controllers that have a SteamVR_WorldPointer assigned. However there are valid reasons that you want only one Worldpointer. Therefore I would suggest to only check if one Worldpointer is assigned at all.

**Comment by thestonefox** [comment] 2016-05-29 11:11
The code checks to see if any controller has a world pointer. Are you saying that if it's not assigned then it throws an error? If so that's a bug and I can fix it

The expected outcome is the teleporter just needs at least one controller.

**Comment by thestonefox** [comment] 2016-05-29 11:18
I see where the problem is. It's been introduced to fix another issue.

I'll fix this either later today or tomorrow

**Comment by spaggi** [comment] 2016-05-29 11:19
Dude, you're awesome. Thanks!

**Comment by thestonefox** [comment] 2016-05-29 11:23
No worries, good spot :)

**Comment by thestonefox** [comment] 2016-05-29 19:09
I'm going to rewrite the way it adds the listeners, at present is rubbish and hacky.

may as well do it properly :)

**Comment by thestonefox** [comment] 2016-05-30 07:19
This commit should fix your problem:
aee1f7e5db3ac6012420d9e7020847f9777d913d

**Comment by thestonefox** [comment] 2016-05-30 16:24
Reopening this as the current implementation is rubbish as well!

I've found a much easier way of doing it and it should solve everything!

**Comment by thestonefox** [comment] 2016-05-30 23:41
Fixed with a much cleaner solution
44e331b434e9993c0954f06d2f74b454f47fa2e8

**Closed by thestonefox** 2016-05-30 23:41 UTC
